Name:           ros-melodic-panda-moveit-config
Version:        0.7.2
Release:        1%{?dist}
Summary:        ROS panda_moveit_config package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-franka-description
Requires:       ros-melodic-joint-state-publisher
Requires:       ros-melodic-moveit-fake-controller-manager
Requires:       ros-melodic-moveit-kinematics
Requires:       ros-melodic-moveit-planners-ompl
Requires:       ros-melodic-moveit-ros-move-group
Requires:       ros-melodic-moveit-ros-visualization
Requires:       ros-melodic-robot-state-publisher
Requires:       ros-melodic-topic-tools
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-franka-description

%description
An automatically generated package with all the configuration and launch files
for using the panda with the MoveIt! Motion Planning Framework

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Jun 04 2019 Mike Lautman <mike@picknik.ai> - 0.7.2-1
- Autogenerated by Bloom

* Mon Dec 10 2018 Mike Lautman <mike@picknik.ai> - 0.7.1-0
- Autogenerated by Bloom

* Tue Nov 13 2018 Mike Lautman <mike@picknik.ai> - 0.7.0-0
- Autogenerated by Bloom

