%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-panda-moveit-config
Version:        0.7.5
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS panda_moveit_config package

License:        BSD
URL:            http://moveit.ros.org/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-franka-description
Requires:       ros-noetic-joint-state-publisher
Requires:       ros-noetic-joint-state-publisher-gui
Requires:       ros-noetic-moveit-fake-controller-manager
Requires:       ros-noetic-moveit-kinematics
Requires:       ros-noetic-moveit-planners-ompl
Requires:       ros-noetic-moveit-ros-move-group
Requires:       ros-noetic-moveit-ros-visualization
Requires:       ros-noetic-robot-state-publisher
Requires:       ros-noetic-topic-tools
Requires:       ros-noetic-xacro
BuildRequires:  ros-noetic-catkin
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
An automatically generated package with all the configuration and launch files
for using the panda with the MoveIt! Motion Planning Framework

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu Mar 25 2021 Mike Lautman <mike@picknik.ai> - 0.7.5-1
- Autogenerated by Bloom

* Thu Mar 25 2021 Mike Lautman <mike@picknik.ai> - 0.7.4-1
- Autogenerated by Bloom

